### ISSUE TITLE
installing for user does not work and system-wide installation throws this error. (Ubuntu 22.04.2 LTS)

### ISSUE THREAD

**Issue by SinghaniaV** [ppvan/nautilus-open-in-blackbox#4]
```
This is run with sudo, install system-wide?[Y/n]y
'nautilus-open-in-blackbox.py' -> '/usr/share/nautilus-python/extensions/nautilus-open-in-blackbox.py'
Restart Nautilus(Files)? [Y/n]y
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-open-in-blackbox.py", line 8, in <module>
    require_version("Nautilus", "4.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 3.0

```

**Comment by ppvan** [comment]
hmm can you show the output of `nautilus --version`?

**Comment by SinghaniaV** [comment]
![image](https://github.com/ppvan/nautilus-open-in-blackbox/assets/75255173/c80870f5-c246-4864-8e29-1f4ad260a663)

**Comment by SinghaniaV** [comment]
> hmm can you show the output of `nautilus --version`?

![image](https://github.com/ppvan/nautilus-open-in-blackbox/assets/75255173/32b51ea3-2d03-473d-988f-7400860d732f)

**Comment by ppvan** [comment]
@SinghaniaV got it, since i migrate this ext to Nautilus 4.0 API, which require Nautilus version >= 43. 
For now you can download [old version](https://github.com/ppvan/nautilus-open-in-blackbox/tree/225d632b114927ae9c036b0ea89c2007f45c64aa) and install as normal. Will work on it soon.

Or you can install latest nautilus 44.2 (not sure if it possible on ubuntu, i use arch btw)
